development: &defaults
  request_sheet: "6741614392567684"
  assignment_sheet: "7678535738386308"
  plan_sheet: "1798319635752836"
  report_sheet: "837690070460292"
  topics_sheet: "2631271533832068"
  ar_details_grantee_column: "Grantee Name"
  ar_objectives_topics_column: "Topics"
  regions:
    "14":
      grantee_names_sheet: "6487185797998468"
      ar_details_sheet: "670348111832964"
      ar_objectives_sheet: "4994248455022468"

production:
  <<: *defaults
  request_sheet: "<%= ENV["SMARTSHEET_REQUEST_SHEET"] %>"
  assignment_sheet: "<%= ENV["SMARTSHEET_ASSIGNMENT_SHEET"] %>"
  plan_sheet: "<%= ENV["SMARTSHEET_PLAN_SHEET"] %>"
  report_sheet: "<%= ENV["SMARTSHEET_REPORT_SHEET"] %>"

test:
  <<: *defaults
  request_sheet: "4419104384804740"
