development: &defaults
  request_sheet: "6741614392567684"
  assignment_sheet: "7678535738386308"
  plan_sheet: "1798319635752836"
  report_sheet: "837690070460292"
  topics_sheet: "2631271533832068"
  ar_details_grantee_column: "Grantee Name"
  ar_objectives_topics_column: "Topics"
  regions:
    "14":
      grantee_names_sheet: "6487185797998468"
      ar_details_sheet: "670348111832964"
      ar_objectives_sheet: "4994248455022468"
      ar_combined_sheet: "6468773273200516"

production:
  request_sheet: "<%= ENV["SMARTSHEET_REQUEST_SHEET"] %>"
  assignment_sheet: "<%= ENV["SMARTSHEET_ASSIGNMENT_SHEET"] %>"
  plan_sheet: "<%= ENV["SMARTSHEET_PLAN_SHEET"] %>"
  report_sheet: "<%= ENV["SMARTSHEET_REPORT_SHEET"] %>"
  topics_sheet: "855262104328308"
  ar_details_grantee_column: "Grantee Name"
  ar_objectives_topics_column: "Topics"
  regions:
    "1":
      grantee_names_sheet: ""
      ar_details_sheet: ""
      ar_objectives_sheet: ""
      ar_combined_sheet: ""
    "2":
      grantee_names_sheet: ""
      ar_details_sheet: ""
      ar_objectives_sheet: ""
      ar_combined_sheet: ""
    "3":
      grantee_names_sheet: ""
      ar_details_sheet: ""
      ar_objectives_sheet: ""
      ar_combined_sheet: ""
    "4":
      grantee_names_sheet: ""
      ar_details_sheet: ""
      ar_objectives_sheet: ""
      ar_combined_sheet: ""
    "5":
      grantee_names_sheet: ""
      ar_details_sheet: ""
      ar_objectives_sheet: ""
      ar_combined_sheet: ""
    "6":
      grantee_names_sheet: ""
      ar_details_sheet: ""
      ar_objectives_sheet: ""
      ar_combined_sheet: ""
    "7":
      grantee_names_sheet: ""
      ar_details_sheet: ""
      ar_objectives_sheet: ""
      ar_combined_sheet: ""
    "8":
      grantee_names_sheet: ""
      ar_details_sheet: ""
      ar_objectives_sheet: ""
      ar_combined_sheet: ""
    "9":
      grantee_names_sheet: ""
      ar_details_sheet: ""
      ar_objectives_sheet: ""
      ar_combined_sheet: ""
    "10":
      grantee_names_sheet: ""
      ar_details_sheet: ""
      ar_objectives_sheet: ""
      ar_combined_sheet: ""
    "11":
      grantee_names_sheet: ""
      ar_details_sheet: ""
      ar_objectives_sheet: ""
      ar_combined_sheet: ""
    "12":
      grantee_names_sheet: ""
      ar_details_sheet: ""
      ar_objectives_sheet: ""
      ar_combined_sheet: ""
    "14":
      grantee_names_sheet: "5331923696818292"
      ar_details_sheet: ""
      ar_objectives_sheet: ""
      ar_combined_sheet: "6543078704486516"

test:
  <<: *defaults
  request_sheet: "4419104384804740"
